version: '3.8'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: xelam11/foodgram_frontend
    volumes:
      - result_build:/app/result_build/build

  nginx:
    image: nginx:1.19.3
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/static/
      - media_value:/media/
      - result_build:/usr/share/nginx/html/
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - frontend

  backend:
    image: xelam11/foodgram
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    env_file:
    - ./.env

volumes:
  result_build:
  postgres_data:
  static_value:
  media_value: